### ISSUE TITLE
popstate event listener

### ISSUE THREAD

**Issue by liaodehui1** [jerrykingxyz/url-change-event#24]
I have two questions about popstate.
1. Why is stopImmediatePropagation called here? The popstate event is fired after the pushstate event is fired, so the stopImmediatePropagation is called, will cause the routing switch to fail.

> https://github.com/jerrykingxyz/url-change-event/blob/master/src/index.js#L10

![20221209-152154](https://user-images.githubusercontent.com/39728398/206647368-9cdfda94-7a47-4727-94e2-430ecdd28a92.gif)

2. Why do you need to call history.go when you cancel here?

> https://github.com/jerrykingxyz/url-change-event/blob/master/src/index.js#L24

In response to the above two questions, I think the popstate event handling implementation may look like this

```
window.addEventListener('popstate', function (e) {
    initState();
    const nowIndex = globalWindow.history.state._index;
    const nowURL = new URL(globalWindow.location.href);
    if (nowIndex !== cacheIndex) {
      const notCanceled = globalWindow.dispatchEvent(
        new UrlChangeEvent({
          oldURL: cacheURL,
          newURL: nowURL,
          action: 'popstate',
        }),
      );
      if (!notCanceled) {
        e.stopImmediatePropagation();
      }
      updateCacheState();
    }
  });
```

**Comment by jerrykingxyz** [comment]
Because of `popstate` cannot prevent the browser's default behavior, so we need to run `history.go` so that the url does not change. But the `history.go` will re-trigger a popstate event, the `stopImmediatePropagation` in first question is to avoid this wrong event to other listener.
PS. Calling `history.pushState()` or `history.replaceState()` won't trigger a popstate event.

**Comment by liaodehui1** [comment]
Ok, I understand.
Question 1 should be a popstate event created using PopstateEvent within the garfish framework.
Question 2 is that I misunderstood.
Thanks!

**Comment by liaodehui1** [comment]
@jerrykingxyz Is it possible to consider compatibility with Garfish? Because Garfish will trigger the popstate event when the route is switched.
![image](https://user-images.githubusercontent.com/39728398/207037175-8861a4c2-1de3-497f-bd2a-398f6a9107b8.png)
Perhaps the event handling for popstate should look like this.
```
window.addEventListener('popstate', function (e) {
  initState()
  const nowIndex = window.history.state._index
  const nowURL = new URL(window.location)

  if (e.garfish && nowIndex === cacheIndex) return;

  if (nowIndex === cacheIndex) {
    e.stopImmediatePropagation()
    return
  }

  const notCanceled = window.dispatchEvent(
    new UrlChangeEvent({
      oldURL: cacheURL,
      newURL: nowURL,
      action: 'popstate',
    })
  )

  if (!notCanceled) {
    e.stopImmediatePropagation()
    window.history.go(cacheIndex - nowIndex)
    return
  }
  updateCacheState()
})
```

**Comment by jerrykingxyz** [comment]
Check framework is not a good idea in this library. This issue seems to be caused by using this lib but not remove side effect in sub project when it be removed, maybe you can

1. Use this library before garfish in the main project
2. remove this polyfill side effects when subproject is removed (not sure if it can be solved)

I will add more micro front end support include re-import check and remove side effect

**Comment by liaodehui1** [comment]
Thanks for your reply!
The route switch triggering popstate is a Garfish design that we cannot modify at this time. You can see https://www.garfishjs.org/guide/router.
